// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2JDmk_jYlOcNsEeNeRdQrWEd4XGLmZw',
    appId: '1:200615030984:web:9cf10314da1a779873b5fd',
    messagingSenderId: '200615030984',
    projectId: 'pedometer-7',
    authDomain: 'pedometer-7.firebaseapp.com',
    storageBucket: 'pedometer-7.appspot.com',
    measurementId: 'G-NXSCDKH5DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLRTTV0dzs4QvDCzhgGCVhAYpp-cuKJac',
    appId: '1:200615030984:android:9d870a8cedba7f2473b5fd',
    messagingSenderId: '200615030984',
    projectId: 'pedometer-7',
    storageBucket: 'pedometer-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRk_gZzGU5UR3q9vfn_pGfN9cGoiyNToU',
    appId: '1:200615030984:ios:30bb46023fa814d873b5fd',
    messagingSenderId: '200615030984',
    projectId: 'pedometer-7',
    storageBucket: 'pedometer-7.appspot.com',
    iosBundleId: 'com.example.pedometerTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRk_gZzGU5UR3q9vfn_pGfN9cGoiyNToU',
    appId: '1:200615030984:ios:625dfa3c51d11bd473b5fd',
    messagingSenderId: '200615030984',
    projectId: 'pedometer-7',
    storageBucket: 'pedometer-7.appspot.com',
    iosBundleId: 'com.example.pedometerTracker.RunnerTests',
  );
}
